terraform-ibm-modules/terraform-ibm-devsecops-alm

- .github/settings.yml
- tests/go.mod
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.
---
> Update repository name

- .github/settings.yml
Updating of the repo name to match the Catalog
---
> fix: update repo name to match catalog

- module-metadata.json
- version.tf
> fix: bump terraform version

- .secrets.baseline
- README.md
- main.tf
- module-metadata.json
- variables.tf
- version.tf
> fix: cc pipeline config repo source

- reference-architectures/deploy-arch-ibm-devsecops-alm.md
> docs: edits and updates

- reference-architectures/deploy-arch-ibm-devsecops-alm.md
> docs: add download link

- README.md
- main.tf
- module-metadata.json
- variables.tf
> ci: update modules

- reference-architectures/deploy-arch-ibm-devsecops-alm.md
> docs: add link to devsecops cloud doc

- README.md
- main.tf
- module-metadata.json
- variables.tf
> ci: reduce SCC params

- .secrets.baseline
- README.md
- examples/default/main.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/main.tf
- examples/devsecops-ci-toolchain-with-key-protect/main.tf
- ibm_catalog.json
- main.tf
- module-metadata.json
- variables.tf
> ci: add catalog json

- reference-architectures/deploy-arch-ibm-devsecops-alm.md
> docs: update deploy arch doc

- README.md
- module-metadata.json
- version.tf
> ci: update terraform version

- reference-architectures/deploy-arch-ibm-devsecops-alm.md
> fix: add link to ref arch doc

- README.md
- ibm_catalog.json
- main.tf
- module-metadata.json
- outputs.tf
- variables.tf
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
If the CI pipeline doesn't run when you …
> fix: projects update failure and update outputs

- main.tf
- module-metadata.json
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
If the CI pipeline doesn't run when you …
> fix: remove volatile timestamp

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .secrets.baseline
migrate to v2 pipeline (had to disable CRA due to apikey issue which will be resolved later)
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when …
> ci: migrate to v2 pipeline

- .github/settings.yml
- README.md
update repo settings to match new pipeline + fixed readme badges
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Your notes help the merger write the commit message for the PR that is published in the release notes for the module.
Run the CI pipeline when the PR is ready for review and …
> ci: update repo settings to match new pipeline

- .github/workflows/ci.yml
- cra-config.yaml
- cra-tf-validate-ignore-rules.json
enable CRA scan
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> ci: enable CRA scan

- examples/default/main.tf
- examples/default/version.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/main.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/variables.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/version.tf
- examples/devsecops-ci-toolchain-with-key-protect/main.tf
- examples/devsecops-ci-toolchain-with-key-protect/variables.tf
- examples/devsecops-ci-toolchain-with-key-protect/version.tf
- module-metadata.json
- outputs.tf
- tests/pr_test.go
> fix: examples

- .github/settings.yml
- .secrets.baseline
- ibm_catalog.json
- add repo topics
- remove `usage` from catalog manifest. DAs are not designed to be embedded into part of another DA solution, they are designed to be the top level solution and not called from any higher level. So in this PR, I am removing the `usage` from the DA manifest which means the DA will no long show the `Embed code` section in the UI:
```
/run pipeline
```
- Include …
> ci: add repo topics + remove usage from catalog manifest

- .github/workflows/ci.yml
- .github/workflows/release.yml
- cra-config.yaml
add toolchain id to cra-config since this repo tests run in different account
```
/run pipeline
```
> ci: add toolchain id to cra-config

- README.md
- code-engine/README.md
- code-engine/main.tf
- code-engine/variables.tf
- examples/default/version.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/version.tf
- examples/devsecops-ci-toolchain-with-key-protect/version.tf
- ibm_catalog.json
- main.tf
- variables.tf
> feat: add signing validation support

- ibm_catalog.json
> fix: catalogjson

- code-engine/main.tf
- code-engine/variables.tf
- code-engine/version.tf
- ibm_catalog.json
> fix: missing "-" from ce name prefix

- code-engine/main.tf
> fix: add missing ce dev region

- .secrets.baseline
- README.md
- code-engine/README.md
- code-engine/main.tf
- code-engine/variables.tf
- examples/variables.tfvars.example
- ibm_catalog.json
- main.tf
- prereqs/main.tf
- prereqs/outputs.tf
- prereqs/provider.tf.example
- prereqs/scripts/gpg_keys.sh
- prereqs/variables.tf
- prereqs/versions.tf
- variables.tf
- version.tf
> feat: add secret and icr namespace creation support

- README.md
- code-engine/README.md
- code-engine/main.tf
- code-engine/outputs.tf
- examples/default/main.tf
- examples/default/version.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/main.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/version.tf
- examples/devsecops-ci-toolchain-with-key-protect/main.tf
- examples/devsecops-ci-toolchain-with-key-protect/version.tf
- main.tf
- outputs.tf
> fix: dependencies, missing output

- code-engine/main.tf
- main.tf
> fix: add count to prefix module

- code-engine/main.tf
- code-engine/variables.tf
- ibm_catalog.json
> fix: prefix duplication due to updated Code Engine DA outputs

- README.md
- version.tf
> ci: pin hashicorp provider versions

- examples/default/main.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/main.tf
- examples/devsecops-ci-toolchain-with-key-protect/main.tf
- ibm_catalog.json
> fix: tests and Code Engine variant name

- ibm_catalog.json
- main.tf
> fix: script path

- README.md
- main.tf
- prereqs/versions.tf
- solutions/code-engine/README.md
- solutions/code-engine/main.tf
- solutions/code-engine/variables.tf
- solutions/code-engine/version.tf
- solutions/kubernetes/README.md
- solutions/kubernetes/main.tf
- solutions/kubernetes/variables.tf
- solutions/kubernetes/version.tf
- variables.tf
- version.tf
> chore: update provider, auto run depends on

- prereqs/main.tf
> fix: missing sm endpoint support iam creds

- main.tf
- prereqs/main.tf
> chore: update policies

- ibm_catalog.json
> fix: scc profile mismatch between variants

- examples/default/main.tf
- examples/default/version.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/main.tf
- examples/devsecops-ci-toolchain-bring-your-own-app/version.tf
- examples/devsecops-ci-toolchain-with-key-protect/main.tf
- examples/devsecops-ci-toolchain-with-key-protect/version.tf
- tests/other_test.go
- tests/pr_test.go
> ci: update tests

- prereqs/main.tf
> chore: update cos policy for cos tool
